export const financialsSchema = {
  id: "financialAnalysis",
  label: "Financial Analysis",
  schema: {
    type: "object",
    properties: {
      // Debit side (To ...)
      openingStockActuals: {
        type: "number",
        title: "To Opening Stock - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      openingStockEstimations: {
        type: "number",
        title: "To Opening Stock - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      purchaseActuals: {
        type: "number",
        title: "To Purchase - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      purchaseEstimations: {
        type: "number",
        title: "To Purchase - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      costOfServicesActuals: {
        type: "number",
        title: "To Cost of Services - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      costOfServicesEstimations: {
        type: "number",
        title: "To Cost of Services - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      wagesActuals: {
        type: "number",
        title: "To Wages - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      wagesEstimations: {
        type: "number",
        title: "To Wages - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      hamaliChargesActuals: {
        type: "number",
        title: "To Hamali Charges - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      hamaliChargesEstimations: {
        type: "number",
        title: "To Hamali Charges - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      manufacturingExpensesActuals: {
        type: "number",
        title: "To Manufacturing Expenses - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      manufacturingExpensesEstimations: {
        type: "number",
        title: "To Manufacturing Expenses - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      packingChargesActuals: {
        type: "number",
        title: "To Packing Charges - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      packingChargesEstimations: {
        type: "number",
        title: "To Packing Charges - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfitDebitActuals: {
        type: "number",
        title: "To Gross Profit - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfitDebitEstimations: {
        type: "number",
        title: "To Gross Profit - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salariesActuals: {
        type: "number",
        title: "To Salaries - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salariesEstimations: {
        type: "number",
        title: "To Salaries - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      rentActuals: {
        type: "number",
        title: "To Rent - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      rentEstimations: {
        type: "number",
        title: "To Rent - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityChargesActuals: {
        type: "number",
        title: "To Electricity Charges - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityChargesEstimations: {
        type: "number",
        title: "To Electricity Charges - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      printingStationeryActuals: {
        type: "number",
        title: "To Printing & Stationery - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      printingStationeryEstimations: {
        type: "number",
        title: "To Printing & Stationery - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneChargesActuals: {
        type: "number",
        title: "To Telephone Charges - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneChargesEstimations: {
        type: "number",
        title: "To Telephone Charges - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      postageTelegramActuals: {
        type: "number",
        title: "To Postage & Telegram - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      postageTelegramEstimations: {
        type: "number",
        title: "To Postage & Telegram - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      officeMaintenanceActuals: {
        type: "number",
        title: "To Office Maintenance - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      officeMaintenanceEstimations: {
        type: "number",
        title: "To Office Maintenance - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      repairsMaintenanceActuals: {
        type: "number",
        title: "To Repairs & Maintenance - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      repairsMaintenanceEstimations: {
        type: "number",
        title: "To Repairs & Maintenance - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadarExpensesActuals: {
        type: "number",
        title: "To Sadar Expenses - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadarExpensesEstimations: {
        type: "number",
        title: "To Sadar Expenses - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditFeeActuals: {
        type: "number",
        title: "To Audit Fee - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditFeeEstimations: {
        type: "number",
        title: "To Audit Fee - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      advertisementActuals: {
        type: "number",
        title: "To Advertisement - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      advertisementEstimations: {
        type: "number",
        title: "To Advertisement - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankChargesActuals: {
        type: "number",
        title: "To Bank Charges - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankChargesEstimations: {
        type: "number",
        title: "To Bank Charges - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      insuranceActuals: {
        type: "number",
        title: "To Insurance - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      insuranceEstimations: {
        type: "number",
        title: "To Insurance - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciationActuals: {
        type: "number",
        title: "To Depreciation - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciationEstimations: {
        type: "number",
        title: "To Depreciation - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interestOnLoanActuals: {
        type: "number",
        title: "To Interest on Loan - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interestOnLoanEstimations: {
        type: "number",
        title: "To Interest on Loan - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfitActuals: {
        type: "number",
        title: "To Net Profit - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfitEstimations: {
        type: "number",
        title: "To Net Profit - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Credit side (By ...)
      salesActuals: {
        type: "number",
        title: "By Sales - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salesEstimations: {
        type: "number",
        title: "By Sales - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      servicesActuals: {
        type: "number",
        title: "By Services - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      servicesEstimations: {
        type: "number",
        title: "By Services - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      closingStockActuals: {
        type: "number",
        title: "By Closing Stock - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      closingStockEstimations: {
        type: "number",
        title: "By Closing Stock - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfitCreditActuals: {
        type: "number",
        title: "By Gross Profit - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfitCreditEstimations: {
        type: "number",
        title: "By Gross Profit - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      rentReceivedActuals: {
        type: "number",
        title: "By Rent Received - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      rentReceivedEstimations: {
        type: "number",
        title: "By Rent Received - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      commissionReceivedActuals: {
        type: "number",
        title: "By Commission Received - Actuals",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      commissionReceivedEstimations: {
        type: "number",
        title: "By Commission Received - Estimations",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
    },
  },
} as const;

export default financialsSchema;
