export const statement3Schema = {
  id: "financialAnalysis",
  label: "Comprehensive Actuals vs Estimated Analysis",
  schema: {
    type: "object",
    properties: {
      // Header Information
      synopsis: {
        type: "string",
        title: "Synopsis of the verification",
        ui: { widget: "textarea", rows: 3 },
      },
      businessName: { type: "string", title: "Business Name", readOnly: true },

      // Opening Stock
      openingStock_2023: {
        type: "number",
        title: `Opening Stock - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      openingStock_2024: {
        type: "number",
        title: `Opening Stock - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      openingStockEstimated: {
        type: "number",
        title: "Opening Stock - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Purchases
      purchases_2023: {
        type: "number",
        title: `Purchases - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      purchases_2024: {
        type: "number",
        title: `Purchases - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      purchasesEstimated: {
        type: "number",
        title: "Purchases - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Gas & Liquid Items
      gasLiquidItems_2023: {
        type: "number",
        title: `Gas & Liquid Items - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gasLiquidItems_2024: {
        type: "number",
        title: `Gas & Liquid Items - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gasLiquidItemsEstimated: {
        type: "number",
        title: "Gas & Liquid Items - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Gross Profit
      grossProfit_2023: {
        type: "number",
        title: `Gross Profit - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "sales_2023 + majuriCharges_2023 + closingStock_2023 - (openingStock_2023 + purchases_2023 + gasLiquidItems_2023)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfit_2024: {
        type: "number",
        title: `Gross Profit - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "sales_2024 + majuriCharges_2024 + closingStock_2024 - (openingStock_2024 + purchases_2024 + gasLiquidItems_2024)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfitEstimated: {
        type: "number",
        title: "Gross Profit - Estimated",
        formula: "salesEstimated + majuriChargesEstimated + closingStockEstimated - (openingStockEstimated + purchasesEstimated + gasLiquidItemsEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Sales (Income Side)
      sales_2023: {
        type: "number",
        title: `Sales - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sales_2024: {
        type: "number",
        title: `Sales - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salesEstimated: {
        type: "number",
        title: "Sales - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Majuri Charges
      majuriCharges_2023: {
        type: "number",
        title: `Majuri Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      majuriCharges_2024: {
        type: "number",
        title: `Majuri Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      majuriChargesEstimated: {
        type: "number",
        title: "Majuri Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Closing Stock
      closingStock_2023: {
        type: "number",
        title: `Closing Stock - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      closingStock_2024: {
        type: "number",
        title: `Closing Stock - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      closingStockEstimated: {
        type: "number",
        title: "Closing Stock - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Indirect Expenses (Estimated Only)
      salaries_2023: {
        type: "number",
        title: `Salaries - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salaries_2024: {
        type: "number",
        title: `Salaries - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salariesEstimated: {
        type: "number",
        title: "Salaries - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bonus_2023: {
        type: "number",
        title: `Bonus - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bonus_2024: {
        type: "number",
        title: `Bonus - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bonusEstimated: {
        type: "number",
        title: "Bonus - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityCharges_2023: {
        type: "number",
        title: `Electricity Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityCharges_2024: {
        type: "number",
        title: `Electricity Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityChargesEstimated: {
        type: "number",
        title: "Electricity Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadar_2023: {
        type: "number",
        title: `Sadar - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadar_2024: {
        type: "number",
        title: `Sadar - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadarEstimated: {
        type: "number",
        title: "Sadar - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      coalGasLiquid_2023: { 
        type: "number",
        title: `Coal, Gas & Liquid - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      coalGasLiquid_2024: {
        type: "number",
        title: `Coal, Gas & Liquid - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      coalGasLiquidEstimated: {
        type: "number",
        title: "Coal, Gas & Liquid - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sparesMachinery_2023: {
        type: "number",
        title: `Spares & Machinery - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sparesMachinery_2024: {
        type: "number",
        title: `Spares & Machinery - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sparesMachineryEstimated: {
        type: "number",
        title: "Spares & Machinery - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankInterest_2023: {
        type: "number",
        title: `Bank Interest - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankInterest_2024: {
        type: "number",
          title: `Bank Interest - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankInterestEstimated: {
        type: "number",
        title: "Bank Interest - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankCharges_2023: {
        type: "number",
        title: `Bank Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankCharges_2024: {
        type: "number",
        title: `Bank Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankChargesEstimated: {
        type: "number",
        title: "Bank Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      financeCharges_2023: {
        type: "number",
        title: `Finance Charges/Professional Tax - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      financeCharges_2024: {
        type: "number",
        title: `Finance Charges/Professional Tax - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      financeChargesEstimated: {
        type: "number",
        title: "Finance Charges/Professional Tax - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      shopRents_2023: {
        type: "number",
        title: `Shop Rents - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      shopRents_2024: {
        type: "number",
        title: `Shop Rents - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      shopRentsEstimated: {
        type: "number",
        title: "Shop Rents - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gstLateFee_2023: {
        type: "number",
        title: `GST Late Fee - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gstLateFee_2024: {
        type: "number",
        title: `GST Late Fee - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gstLateFeeEstimated: {
        type: "number",
        title: "GST Late Fee - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditorFee_2023: {
        type: "number",
        title: `Auditor Fee - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditorFee_2024: {
        type: "number",
        title: `Auditor Fee - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditorFeeEstimated: {
        type: "number",
        title: "Auditor Fee - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneCharges_2023: {
        type: "number",
        title: `Telephone Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneCharges_2024: {
        type: "number",
          title: `Telephone Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneChargesEstimated: {
        type: "number",
        title: "Telephone Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      travellingExp_2023: {
        type: "number",
        title: `Travelling Exp/Transport - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      travellingExp_2024: {
        type: "number",
        title: `Travelling Exp/Transport - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      travellingExpEstimated: {
        type: "number",
        title: "Travelling Exp/Transport - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      vehicleMaintenance_2023: {
        type: "number",
        title: `Vehicle Maintenance & machinery - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      vehicleMaintenance_2024: {
        type: "number",
        title: `Vehicle Maintenance & machinery - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      vehicleMaintenanceEstimated: {
        type: "number",
        title: "Vehicle Maintenance & machinery - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciation_2023: {
        type: "number",
        title: `Depreciation - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciation_2024: {
        type: "number",
        title: `Depreciation - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciationEstimated: {
        type: "number",
        title: "Depreciation - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interest_2023: {
        type: "number",
        title: `Interest - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interest_2024: {
        type: "number",
        title: `Interest - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interestEstimated: {
        type: "number",
        title: "Interest - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfit_2023: {
        type: "number",
        title: `Net Profit - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "grossProfit_2023 - (salaries_2023 + bonus_2023 + electricityCharges_2023 + sadar_2023 + coalGasLiquid_2023 + sparesMachinery_2023 + bankInterest_2023 + bankCharges_2023 + financeCharges_2023 + shopRents_2023 + gstLateFee_2023 + auditorFee_2023 + telephoneCharges_2023 + travellingExp_2023 + vehicleMaintenance_2023 + depreciation_2023 + interest_2023)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfit_2024: {
        type: "number",
        title: `Net Profit - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "grossProfit_2024 - (salaries_2024 + bonus_2024 + electricityCharges_2024 + sadar_2024 + coalGasLiquid_2024 + sparesMachinery_2024 + bankInterest_2024 + bankCharges_2024 + financeCharges_2024 + shopRents_2024 + gstLateFee_2024 + auditorFee_2024 + telephoneCharges_2024 + travellingExp_2024 + vehicleMaintenance_2024 + depreciation_2024 + interest_2024)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfitEstimated: {
        type: "number",
        title: "Net Profit - Estimated",
        formula: "grossProfitEstimated - (salariesEstimated + bonusEstimated + electricityChargesEstimated + sadarEstimated + coalGasLiquidEstimated + sparesMachineryEstimated + bankInterestEstimated + bankChargesEstimated + financeChargesEstimated + shopRentsEstimated + gstLateFeeEstimated + auditorFeeEstimated + telephoneChargesEstimated + travellingExpEstimated + vehicleMaintenanceEstimated + depreciationEstimated + interestEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Total (Left And Right)
      total_2023_left: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "openingStock_2023 + purchases_2023 + gasLiquidItems_2023 + grossProfit_2023 + salaries_2023 + bonus_2023 + electricityCharges_2023 + sadar_2023 + coalGasLiquid_2023 + sparesMachinery_2023 + bankInterest_2023 + bankCharges_2023 + financeCharges_2023 + shopRents_2023 + gstLateFee_2023 + auditorFee_2023 + telephoneCharges_2023 + travellingExp_2023 + vehicleMaintenance_2023 + depreciation_2023 + interest_2023 + netProfit_2023",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_2024_left: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "openingStock_2024 + purchases_2024 + gasLiquidItems_2024 + grossProfit_2024 + salaries_2024 + bonus_2024 + electricityCharges_2024 + sadar_2024 + coalGasLiquid_2024 + sparesMachinery_2024 + bankInterest_2024 + bankCharges_2024 + financeCharges_2024 + shopRents_2024 + gstLateFee_2024 + auditorFee_2024 + telephoneCharges_2024 + travellingExp_2024 + vehicleMaintenance_2024 + depreciation_2024 + interest_2024 + netProfit_2024",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_estimated_left: {
        type: "number",
        title: "Total - Estimated",
        formula: "openingStockEstimated + purchasesEstimated + gasLiquidItemsEstimated + grossProfitEstimated + salariesEstimated + bonusEstimated + electricityChargesEstimated + sadarEstimated + coalGasLiquidEstimated + sparesMachineryEstimated + bankInterestEstimated + bankChargesEstimated + financeChargesEstimated + shopRentsEstimated + gstLateFeeEstimated + auditorFeeEstimated + telephoneChargesEstimated + travellingExpEstimated + vehicleMaintenanceEstimated + depreciationEstimated + interestEstimated + netProfitEstimated",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_2023_right: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "sales_2023 + majuriCharges_2023 + closingStock_2023 + grossProfit_2023",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },  
      total_2024_right: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "sales_2024 + majuriCharges_2024 + closingStock_2024 + grossProfit_2024",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_estimated_right: {
        type: "number",
        title: "Total - Estimated",
        formula: "salesEstimated + majuriChargesEstimated + closingStockEstimated + grossProfitEstimated",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Monthly Calculations
      monthlyTurnover: {
        type: "number",
        title: "Monthly Turnover",
        formula: "(salesEstimated) / 12",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      monthlyPayments: {
        type: "number",
        title: "Monthly Payments",
        formula: "monthlyTurnover - (monthlyNetProfit)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      monthlyNetProfit: {
        type: "number",
        title: "Monthly Net Profit",
        formula: "netProfitEstimated / 12",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Margin Percentages
      gpPercentage: {
        type: "number",
        title: "Gross Profit %",
        formula: "grossProfitEstimated / (salesEstimated+majuriChargesEstimated+closingStockEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      npPercentage: {
        type: "number",
        title: "Net Profit %",
        formula: "netProfitEstimated / (salesEstimated+majuriChargesEstimated+closingStockEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Balance Sheet
      balanceSheetleft: {
        type: "object",
        title: "Balance Sheet Left",
        properties: {
          capital_2023: {
            type: "number",
            title: `Capital - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          capital_2024: {
            type: "number",
            title: `Capital - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          capitalEstimated: {
            type: "number",
            title: "Capital - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbiCc_2023: {
            type: "number",
            title: `SBI CC - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbiCc_2024: {
            type: "number",
            title: `SBI CC - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbiCcEstimated: {
            type: "number",
            title: "SBI CC - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          hdfcVl_2023: {
            type: "number",
            title: `HDFC VL - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          hdfcVl_2024: {
            type: "number",
            title: `HDFC VL - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          hdfcVlEstimated: {
            type: "number",
            title: "HDFC VL - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sundryCreditors_2023: {
            type: "number",
            title: `Sundry Creditors - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sundryCreditors_2024: {
            type: "number",
            title: `Sundry Creditors - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sundryCreditorsEstimated: {
            type: "number",
            title: "Sundry Creditors - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          provAuditorFee_2023: {
            type: "number",
            title: `Prov Auditor Fee - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          provAuditorFee_2024: {
            type: "number",
            title: `Prov Auditor Fee - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          provAuditorFeeEstimated: {
            type: "number",
            title: "Prov Auditor Fee - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          growthScoreLoan_2023: {
            type: "number",
            title: `Growth Score Loan - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          growthScoreLoan_2024: {
            type: "number",
            title: `Growth Score Loan - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          growthScoreLoanEstimated: {
            type: "number",
            title: "Growth Score Loan - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          poonwalaFincorp_2023: {
            type: "number",
            title: `Poonwala Fincorp - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          poonwalaFincorp_2024: {
            type: "number",
            title: `Poonwala Fincorp - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          poonwalaFincorpEstimated: {
            type: "number",
            title: "Poonwala Fincorp - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          lendingKartLoan_2023: {
            type: "number",
            title: `Lending Kart Loan - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          lendingKartLoan_2024: {
            type: "number",
            title: `Lending Kart Loan - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          lendingKartLoanEstimated: {
            type: "number",
            title: "Lending Kart Loan - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          tdsTcsPayable_2023: {
            type: "number",
            title: `TDS/TCS Payable - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          tdsTcsPayable_2024: {
            type: "number",
            title: `TDS/TCS Payable - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          tdsTcsPayableEstimated: {
            type: "number",
            title: "TDS/TCS Payable - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          total_2023: {
            type: "number",
            title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            formula: "capital_2023 + sbiCc_2023 + hdfcVl_2023 + sundryCreditors_2023 + provAuditorFee_2023 + growthScoreLoan_2023 + poonwalaFincorp_2023 + lendingKartLoan_2023 + tdsTcsPayable_2023",
            readOnly: true,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          total_2024: {
            type: "number",
            title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            formula: "capital_2024 + sbiCc_2024 + hdfcVl_2024 + sundryCreditors_2024 + provAuditorFee_2024 + growthScoreLoan_2024 + poonwalaFincorp_2024 + lendingKartLoan_2024 + tdsTcsPayable_2024",
            readOnly: true,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          totalEstimated: {
            type: "number",
            title: "Total - Estimated",
            formula: "capitalEstimated + sbiCcEstimated + hdfcVlEstimated + sundryCreditorsEstimated + provAuditorFeeEstimated + growthScoreLoanEstimated + poonwalaFincorpEstimated + lendingKartLoanEstimated + tdsTcsPayableEstimated",
            readOnly: true,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
        },
      },
      balanceSheetright: {
        type: "object",
        title: "Balance Sheet Right",
        properties: {
          cashOnHand_2023: {
            type: "number",
            title: `Cash on Hand - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          cashOnHand_2024: {
            type: "number",
            title: `Cash on Hand - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          cashOnHandEstimated: {
            type: "number",
            title: "Cash on Hand - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          federalBank_2023: {
            type: "number",
            title: `Federal bank - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          federalBank_2024: {
            type: "number",
            title: `Federal bank - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          federalBankEstimated: {
            type: "number",
            title: "Federal bank - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbhCaHdfcCa_2023: {
            type: "number",
            title: `SBH CA/HDFC CA - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbhCaHdfcCa_2024: {
            type: "number",
            title: `SBH CA/HDFC CA - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbhCaHdfcCaEstimated: {
            type: "number",
            title: "SBH CA/HDFC CA - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbhSbHdfcSb_2023: {
            type: "number",
            title: `SBH SB/ HDFC SB - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbhSbHdfcSb_2024: {
            type: "number",
            title: `SBH SB/ HDFC SB - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sbhSbHdfcSbEstimated: {
            type: "number",
            title: "SBH SB/ HDFC SB - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          karnatakaBank_2023: {
            type: "number",
            title: `KARNATAKA BANK - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          karnatakaBank_2024: {
            type: "number",
            title: `KARNATAKA BANK - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          karnatakaBankEstimated: {
            type: "number",
            title: "KARNATAKA BANK - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          furniture_2023: {
            type: "number",
            title: `Furniture - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          furniture_2024: {
            type: "number",
            title: `Furniture - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          furnitureEstimated: {
            type: "number",
            title: "Furniture - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          eleWeightsMeasurements_2023: {
            type: "number",
            title: `Measurements - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          eleWeightsMeasurements_2024: {
            type: "number",
            title: `Measurements - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          eleWeightsMeasurementsEstimated: {
            type: "number",
            title: "Measurements - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          machinery_2023: {
            type: "number",
            title: `Machinery - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          machinery_2024: {
            type: "number",
            title: `Machinery - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          machineryEstimated: {
            type: "number",
            title: "Machinery - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          car_2023: {
            type: "number",
            title: `Car - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          car_2024: {
            type: "number",
            title: `Car - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          carEstimated: {
            type: "number",
            title: "Car - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          openPlots_2023: {
            type: "number",
            title: `Open Plots - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          openPlots_2024: {
            type: "number",
            title: `Open Plots - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          openPlotsEstimated: {
            type: "number",
            title: "Open Plots - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          houseProperty_2023: {
            type: "number",
            title: `House Property - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          houseProperty_2024: {
            type: "number",
            title: `House Property - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          housePropertyEstimated: {
            type: "number",
            title: "House Property - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          houseConstruction_2023: {
            type: "number",
            title: `HouseConstruction - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          houseConstruction_2024: {
            type: "number",
            title: `HouseConstruction - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          houseConstructionEstimated: {
            type: "number",
            title: "HouseConstruction - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          closingStock_2023: {
            type: "number",
            title: `Closing Stock - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          closingStock_2024: {
            type: "number",
            title: `Closing Stock - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          closingStockEstimated: {
            type: "number",
            title: "Closing Stock - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          gstReceivable_2023: {
            type: "number",
            title: `GST Receivable - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          gstReceivable_2024: {
            type: "number",
            title: `GST Receivable - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          gstReceivableEstimated: {
            type: "number",
            title: "GST Receivable - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          deposits_2023: {
            type: "number",
            title: `Deposits - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          deposits_2024: {
            type: "number",
            title: `Deposits - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          depositsEstimated: {
            type: "number",
            title: "Deposits - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sundryDebtors_2023: {
            type: "number",
            title: `Sundry Debtors - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sundryDebtors_2024: {
            type: "number",
            title: `Sundry Debtors - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          sundryDebtorsEstimated: {
            type: "number",
            title: "Sundry Debtors - Estimated",
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          total_2023: {
            type: "number",
            title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
            formula: "cashOnHand_2023 + federalBank_2023 + sbhCaHdfcCa_2023 + sbhSbHdfcSb_2023 + karnatakaBank_2023 + furniture_2023 + eleWeightsMeasurements_2023 + machinery_2023 + car_2023 + openPlots_2023 + houseProperty_2023 + houseConstruction_2023 + closingStock_2023 + gstReceivable_2023 + deposits_2023 + sundryDebtors_2023",
            readOnly: true,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          total_2024: {
            type: "number",
            title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
            formula: "cashOnHand_2024 + federalBank_2024 + sbhCaHdfcCa_2024 + sbhSbHdfcSb_2024 + karnatakaBank_2024 + furniture_2024 + eleWeightsMeasurements_2024 + machinery_2024 + car_2024 + openPlots_2024 + houseProperty_2024 + houseConstruction_2024 + closingStock_2024 + gstReceivable_2024 + deposits_2024 + sundryDebtors_2024",
            readOnly: true,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
          totalEstimated: {
            type: "number",
            title: "Total - Estimated",
            formula: "cashOnHandEstimated + federalBankEstimated + sbhCaHdfcCaEstimated + sbhSbHdfcSbEstimated + karnatakaBankEstimated + furnitureEstimated + eleWeightsMeasurementsEstimated + machineryEstimated + carEstimated + openPlotsEstimated + housePropertyEstimated + houseConstructionEstimated + closingStockEstimated + gstReceivableEstimated + depositsEstimated + sundryDebtorsEstimated",
            readOnly: true,
            minimum: 0,
            formatter: {
              useIndianFormat: true,
              locale: "en-IN",
              maxDecimalPlaces: 2,
              minDecimalPlaces: 0,
            },
          },
        },
      },
    },
    // Debit side (expenses/costs) - Left column
    debit: [
      "openingStock_2023",
      "openingStock_2024",
      "openingStockEstimated",
      "purchases_2023",
      "purchases_2024",
      "purchasesEstimated",
      "gasLiquidItems_2023",
      "gasLiquidItems_2024",
      "gasLiquidItemsEstimated",
      "salaries_2023",
      "salaries_2024",
      "salariesEstimated",
      "bonus_2023",
      "bonus_2024",
      "bonusEstimated",
      "electricityCharges_2023",
      "electricityCharges_2024",
      "electricityChargesEstimated",
      "sadar_2023",
      "sadar_2024",
      "sadarEstimated",
      "coalGasLiquid_2023",
      "coalGasLiquid_2024",
      "coalGasLiquidEstimated",
      "sparesMachinery_2023",
      "sparesMachinery_2024",
      "sparesMachineryEstimated",
      "bankInterest_2023",
      "bankInterest_2024",
      "bankInterestEstimated",
      "bankCharges_2023",
      "bankCharges_2024",
      "bankChargesEstimated",
      "financeCharges_2023",
      "financeCharges_2024",
      "financeChargesEstimated",
      "shopRents_2023",
      "shopRents_2024",
      "shopRentsEstimated",
      "gstLateFee_2023",
      "gstLateFee_2024",
      "gstLateFeeEstimated",
      "auditorFee_2023",
      "auditorFee_2024",
      "auditorFeeEstimated",
      "telephoneCharges_2023",
      "telephoneCharges_2024",
      "telephoneChargesEstimated",
      "travellingExp_2023",
      "travellingExp_2024",
      "travellingExpEstimated",
      "vehicleMaintenance_2023",
      "vehicleMaintenance_2024",
      "vehicleMaintenanceEstimated",
      "depreciation_2023",
      "depreciation_2024",
      "depreciationEstimated",
      "interest_2023",
      "interest_2024",
      "interestEstimated",
      "netProfit_2023",
      "netProfit_2024",
      "netProfitEstimated",
      "total_2023_left",
      "total_2024_left",
      "total_estimated_left",
    ],
    // Credit side (income/receipts) - Right column
    credit: [
      "sales_2023",
      "sales_2024",
      "salesEstimated",
      "majuriCharges_2023",
      "majuriCharges_2024",
      "majuriChargesEstimated",
      "closingStock_2023",
      "closingStock_2024",
      "closingStockEstimated",
      "total_2023_right",
      "total_2024_right",
      "total_estimated_right",
    ],
  },
} as const;

export default statement3Schema;
