export const statement3Schema = {
  id: "financialAnalysis",
  label: "Comprehensive Actuals vs Estimated Analysis",
  schema: {
    type: "object",
    properties: {
      // Header Information
      synopsis: {
        type: "string",
        title: "Synopsis of the verification",
        ui: { widget: "textarea", rows: 3 },
      },
      businessName: { type: "string", title: "Business Name", readOnly: true },

      // Opening Stock
      openingStock_2023: {
        type: "number",
        title: `Opening Stock - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      openingStock_2024: {
        type: "number",
        title: `Opening Stock - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      openingStockChange: {
        type: "number",
        title: "Opening Stock - Change %",
        formula:
          "((openingStock_2024 - openingStock_2023) / openingStock_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      openingStockEstimated: {
        type: "number",
        title: "Opening Stock - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Purchases
      purchases_2023: {
        type: "number",
        title: `Purchases - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      purchases_2024: {
        type: "number",
        title: `Purchases - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      purchasesChange: {
        type: "number",
        title: "Purchases - Change %",
        formula: "((purchases_2024 - purchases_2023) / purchases_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      purchasesEstimated: {
        type: "number",
        title: "Purchases - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Gas & Liquid Items
      gasLiquidItems_2023: {
        type: "number",
        title: `Gas & Liquid Items - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gasLiquidItems_2024: {
        type: "number",
        title: `Gas & Liquid Items - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gasLiquidItemsChange: {
        type: "number",
        title: "Gas & Liquid Items - Change %",
        formula:
          "((gasLiquidItems_2024 - gasLiquidItems_2023) / gasLiquidItems_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gasLiquidItemsEstimated: {
        type: "number",
        title: "Gas & Liquid Items - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Gross Profit
      grossProfit_2023: {
        type: "number",
        title: `Gross Profit - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "sales_2023 + majuriCharges_2023 + closingStock_2023 - (openingStock_2023 + purchases_2023 + gasLiquidItems_2023)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfit_2024: {
        type: "number",
        title: `Gross Profit - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "sales_2024 + majuriCharges_2024 + closingStock_2024 - (openingStock_2024 + purchases_2024 + gasLiquidItems_2024)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfitChange: {
        type: "number",
        title: "Gross Profit - Change %",
        formula:
          "((grossProfit_2024 - grossProfit_2023) / grossProfit_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      grossProfitEstimated: {
        type: "number",
        title: "Gross Profit - Estimated",
        formula: "salesEstimated + majuriChargesEstimated + closingStockEstimated - (openingStockEstimated + purchasesEstimated + gasLiquidItemsEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Sales (Income Side)
      sales_2023: {
        type: "number",
        title: `Sales - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sales_2024: {
        type: "number",
        title: `Sales - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salesChange: {
        type: "number",
        title: "Sales - Change %",
        formula: "((sales_2024 - sales_2023) / sales_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salesEstimated: {
        type: "number",
        title: "Sales - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Majuri Charges
      majuriCharges_2023: {
        type: "number",
        title: `Majuri Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      majuriCharges_2024: {
        type: "number",
        title: `Majuri Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      majuriChargesChange: {
        type: "number",
        title: "Majuri Charges - Change %",
        formula:
          "((majuriCharges_2024 - majuriCharges_2023) / majuriCharges_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      majuriChargesEstimated: {
        type: "number",
        title: "Majuri Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Closing Stock
      closingStock_2023: {
        type: "number",
        title: `Closing Stock - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      closingStock_2024: {
        type: "number",
        title: `Closing Stock - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      closingStockChange: {
        type: "number",
        title: "Closing Stock - Change %",
        formula:
          "((closingStock_2024 - closingStock_2023) / closingStock_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      closingStockEstimated: {
        type: "number",
        title: "Closing Stock - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Indirect Expenses (Estimated Only)
      salaries_2023: {
        type: "number",
        title: `Salaries - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salaries_2024: {
        type: "number",
        title: `Salaries - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salariesChange: {
        type: "number",
        title: "Salaries - Change %",
        formula: "((salaries_2024 - salaries_2023) / salaries_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      salariesEstimated: {
        type: "number",
        title: "Salaries - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bonus_2023: {
        type: "number",
        title: `Bonus - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bonus_2024: {
        type: "number",
        title: `Bonus - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bonusChange: {
        type: "number",
        title: "Bonus - Change %",
        formula: "((bonus_2024 - bonus_2023) / bonus_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bonusEstimated: {
        type: "number",
        title: "Bonus - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityCharges_2023: {
        type: "number",
        title: `Electricity Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityCharges_2024: {
        type: "number",
        title: `Electricity Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityChargesChange: {
        type: "number",
        title: "Electricity Charges - Change %",
        formula: "((electricityCharges_2024 - electricityCharges_2023) / electricityCharges_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      electricityChargesEstimated: {
        type: "number",
        title: "Electricity Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadar_2023: {
        type: "number",
        title: `Sadar - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadar_2024: {
        type: "number",
        title: `Sadar - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadarChange: {
        type: "number",
        title: "Sadar - Change %",
        formula: "((sadar_2024 - sadar_2023) / sadar_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sadarEstimated: {
        type: "number",
        title: "Sadar - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      coalGasLiquid_2023: { 
        type: "number",
        title: `Coal, Gas & Liquid - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      coalGasLiquid_2024: {
        type: "number",
        title: `Coal, Gas & Liquid - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      coalGasLiquidChange: {
        type: "number",
        title: "Coal, Gas & Liquid - Change %",
        formula: "((coalGasLiquid_2024 - coalGasLiquid_2023) / coalGasLiquid_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      coalGasLiquidEstimated: {
        type: "number",
        title: "Coal, Gas & Liquid - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sparesMachinery_2023: {
        type: "number",
        title: `Spares & Machinery - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sparesMachinery_2024: {
        type: "number",
        title: `Spares & Machinery - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sparesMachineryChange: {
        type: "number",
        title: "Spares & Machinery - Change %",
        formula: "((sparesMachinery_2024 - sparesMachinery_2023) / sparesMachinery_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      sparesMachineryEstimated: {
        type: "number",
        title: "Spares & Machinery - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankInterest_2023: {
        type: "number",
        title: `Bank Interest - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankInterest_2024: {
        type: "number",
          title: `Bank Interest - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankInterestChange: {
        type: "number",
        title: "Bank Interest - Change %",
        formula: "((bankInterest_2024 - bankInterest_2023) / bankInterest_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankInterestEstimated: {
        type: "number",
        title: "Bank Interest - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankCharges_2023: {
        type: "number",
        title: `Bank Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankCharges_2024: {
        type: "number",
        title: `Bank Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankChargesChange: {
        type: "number",
        title: "Bank Charges - Change %",
        formula: "((bankCharges_2024 - bankCharges_2023) / bankCharges_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      bankChargesEstimated: {
        type: "number",
        title: "Bank Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      financeCharges_2023: {
        type: "number",
        title: `Finance Charges/Professional Tax - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      financeCharges_2024: {
        type: "number",
        title: `Finance Charges/Professional Tax - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      financeChargesChange: {
        type: "number",
        title: "Finance Charges/Professional Tax - Change %",
        formula: "((financeCharges_2024 - financeCharges_2023) / financeCharges_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      financeChargesEstimated: {
        type: "number",
        title: "Finance Charges/Professional Tax - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      shopRents_2023: {
        type: "number",
        title: `Shop Rents - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      shopRents_2024: {
        type: "number",
        title: `Shop Rents - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      shopRentsChange: {
        type: "number",
        title: "Shop Rents - Change %",
        formula: "((shopRents_2024 - shopRents_2023) / shopRents_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      shopRentsEstimated: {
        type: "number",
        title: "Shop Rents - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gstLateFee_2023: {
        type: "number",
        title: `GST Late Fee - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gstLateFee_2024: {
        type: "number",
        title: `GST Late Fee - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gstLateFeeChange: {
        type: "number",
        title: "GST Late Fee - Change %",
        formula: "((gstLateFee_2024 - gstLateFee_2023) / gstLateFee_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      gstLateFeeEstimated: {
        type: "number",
        title: "GST Late Fee - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditorFee_2023: {
        type: "number",
        title: `Auditor Fee - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditorFee_2024: {
        type: "number",
        title: `Auditor Fee - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditorFeeChange: {
        type: "number",
        title: "Auditor Fee - Change %",
        formula: "((auditorFee_2024 - auditorFee_2023) / auditorFee_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      auditorFeeEstimated: {
        type: "number",
        title: "Auditor Fee - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneCharges_2023: {
        type: "number",
        title: `Telephone Charges - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneCharges_2024: {
        type: "number",
          title: `Telephone Charges - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneChargesChange: {
        type: "number",
        title: "Telephone Charges - Change %",
        formula: "((telephoneCharges_2024 - telephoneCharges_2023) / telephoneCharges_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      telephoneChargesEstimated: {
        type: "number",
        title: "Telephone Charges - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      travellingExp_2023: {
        type: "number",
        title: `Travelling Exp/Transport - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      travellingExp_2024: {
        type: "number",
        title: `Travelling Exp/Transport - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      travellingExpChange: {
        type: "number",
        title: "Travelling Exp/Transport - Change %",
        formula: "((travellingExp_2024 - travellingExp_2023) / travellingExp_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      travellingExpEstimated: {
        type: "number",
        title: "Travelling Exp/Transport - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      vehicleMaintenance_2023: {
        type: "number",
        title: `Vehicle Maintenance & machinery - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      vehicleMaintenance_2024: {
        type: "number",
        title: `Vehicle Maintenance & machinery - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      vehicleMaintenanceChange: {
        type: "number",
        title: "Vehicle Maintenance & machinery - Change %",
        formula: "((vehicleMaintenance_2024 - vehicleMaintenance_2023) / vehicleMaintenance_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      vehicleMaintenanceEstimated: {
        type: "number",
        title: "Vehicle Maintenance & machinery - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciation_2023: {
        type: "number",
        title: `Depreciation - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciation_2024: {
        type: "number",
        title: `Depreciation - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciationChange: {
        type: "number",
        title: "Depreciation - Change %",
        formula: "((depreciation_2024 - depreciation_2023) / depreciation_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      depreciationEstimated: {
        type: "number",
        title: "Depreciation - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interest_2023: {
        type: "number",
        title: `Interest - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interest_2024: {
        type: "number",
        title: `Interest - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interestChange: {
        type: "number",
        title: "Interest - Change %",
        formula: "((interest_2024 - interest_2023) / interest_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      interestEstimated: {
        type: "number",
        title: "Interest - Estimated",
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfit_2023: {
        type: "number",
        title: `Net Profit - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "grossProfit_2023 - (salaries_2023 + bonus_2023 + electricityCharges_2023 + sadar_2023 + coalGasLiquid_2023 + sparesMachinery_2023 + bankInterest_2023 + bankCharges_2023 + financeCharges_2023 + shopRents_2023 + gstLateFee_2023 + auditorFee_2023 + telephoneCharges_2023 + travellingExp_2023 + vehicleMaintenance_2023 + depreciation_2023 + interest_2023)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfit_2024: {
        type: "number",
        title: `Net Profit - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "grossProfit_2024 - (salaries_2024 + bonus_2024 + electricityCharges_2024 + sadar_2024 + coalGasLiquid_2024 + sparesMachinery_2024 + bankInterest_2024 + bankCharges_2024 + financeCharges_2024 + shopRents_2024 + gstLateFee_2024 + auditorFee_2024 + telephoneCharges_2024 + travellingExp_2024 + vehicleMaintenance_2024 + depreciation_2024 + interest_2024)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfitChange: {
        type: "number",
        title: "Net Profit - Change %",
        formula: "((netProfit_2024 - netProfit_2023) / netProfit_2023) * 100",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      netProfitEstimated: {
        type: "number",
        title: "Net Profit - Estimated",
        formula: "grossProfitEstimated - (salariesEstimated + bonusEstimated + electricityChargesEstimated + sadarEstimated + coalGasLiquidEstimated + sparesMachineryEstimated + bankInterestEstimated + bankChargesEstimated + financeChargesEstimated + shopRentsEstimated + gstLateFeeEstimated + auditorFeeEstimated + telephoneChargesEstimated + travellingExpEstimated + vehicleMaintenanceEstimated + depreciationEstimated + interestEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Total (Left And Right)
      total_2023_left: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "openingStock_2023 + purchases_2023 + gasLiquidItems_2023 + grossProfit_2023 + salaries_2023 + bonus_2023 + electricityCharges_2023 + sadar_2023 + coalGasLiquid_2023 + sparesMachinery_2023 + bankInterest_2023 + bankCharges_2023 + financeCharges_2023 + shopRents_2023 + gstLateFee_2023 + auditorFee_2023 + telephoneCharges_2023 + travellingExp_2023 + vehicleMaintenance_2023 + depreciation_2023 + interest_2023 + netProfit_2023",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_2024_left: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "openingStock_2024 + purchases_2024 + gasLiquidItems_2024 + grossProfit_2024 + salaries_2024 + bonus_2024 + electricityCharges_2024 + sadar_2024 + coalGasLiquid_2024 + sparesMachinery_2024 + bankInterest_2024 + bankCharges_2024 + financeCharges_2024 + shopRents_2024 + gstLateFee_2024 + auditorFee_2024 + telephoneCharges_2024 + travellingExp_2024 + vehicleMaintenance_2024 + depreciation_2024 + interest_2024 + netProfit_2024",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_estimated_left: {
        type: "number",
        title: "Total - Estimated",
        formula: "openingStockEstimated + purchasesEstimated + gasLiquidItemsEstimated + grossProfitEstimated + salariesEstimated + bonusEstimated + electricityChargesEstimated + sadarEstimated + coalGasLiquidEstimated + sparesMachineryEstimated + bankInterestEstimated + bankChargesEstimated + financeChargesEstimated + shopRentsEstimated + gstLateFeeEstimated + auditorFeeEstimated + telephoneChargesEstimated + travellingExpEstimated + vehicleMaintenanceEstimated + depreciationEstimated + interestEstimated + netProfitEstimated",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_2023_right: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 2}`,
        formula: "sales_2023 + majuriCharges_2023 + closingStock_2023 + grossProfit_2023",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },  
      total_2024_right: {
        type: "number",
        title: `Total - Actuals as on 31/03/${new Date().getFullYear() - 1}`,
        formula: "sales_2024 + majuriCharges_2024 + closingStock_2024 + grossProfit_2024",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      total_estimated_right: {
        type: "number",
        title: "Total - Estimated",
        formula: "salesEstimated + majuriChargesEstimated + closingStockEstimated + grossProfitEstimated",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Monthly Calculations
      monthlyTurnover: {
        type: "number",
        title: "Monthly Turnover",
        formula: "(salesEstimated) / 12",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      monthlyPayments: {
        type: "number",
        title: "Monthly Payments",
        formula: "monthlyTurnover - (monthlyNetProfit)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      monthlyNetProfit: {
        type: "number",
        title: "Monthly Net Profit",
        formula: "netProfitEstimated / 12",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },

      // Margin Percentages
      gpPercentage: {
        type: "number",
        title: "Gross Profit %",
        formula: "grossProfitEstimated / (salesEstimated+majuriChargesEstimated+closingStockEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
      npPercentage: {
        type: "number",
        title: "Net Profit %",
        formula: "netProfitEstimated / (salesEstimated+majuriChargesEstimated+closingStockEstimated)",
        readOnly: true,
        minimum: 0,
        formatter: {
          useIndianFormat: true,
          locale: "en-IN",
          maxDecimalPlaces: 2,
          minDecimalPlaces: 0,
        },
      },
    },
  },
} as const;

export default statement3Schema;
