// Auto-generated by scripts/split-forms.js

import axisFinanceUblAbove10lSchema from "./axis-finance-ubl-above-10l";
import axisFinanceUblBelow10lSchema from "./axis-finance-ubl-below-10l";
import axisBankSchema from "./axis-bank";
import arkaFincapSchema from "./arka-fincap";
import tataUblSchema from "./tata-ubl";
import rblSchema from "./rbl";
import herohousingSalariedSchema from "./herohousing-salaried";
import herohousingSelfSchema from "./herohousing-self";
import cholaSchema from "./chola";
import dcbSchema from "./dcb";
import heroFincorpSchema from "./hero-fincorp";
import iciciSchema from "./icici";
import idfcHlMlSchema from "./idfc-hl-ml";
import idfcPlSchema from "./idfc-pl";
import iiflSchema from "./iifl";
import niwasSalariedSchema from "./niwas-salaried";
import niwasSenpSchema from "./niwas-senp";
import yesBankSchema from "./yes-bank";
import smfgSmeSchema from "./smfg-sme";
import indiaShelterSenpSchema from "./india-shelter-senp";
import indiaShelterSalariedSchema from "./india-shelter-salaried";
import incredSchema from "./incred";
import axisAgriSchema from "./axis-agri";
import adityaBirlaSchema from "./aditya-birla";
import ambitSchema from "./ambit";
import ambitMsmeSchema from "./ambit-msme";
import axisFinanceSchema from "./axis-finance";
import janaSalariedSchema from "./jana-salaried";
import janaSenpAbove50lSchema from "./jana-senp-above-50l";
import janaSenpBelow50lSchema from "./jana-senp-below-50l";

export interface BankSchemaConfig {
  bankName: string;
  schema: any;
  templatesAndFooters: Record<string, string>;
}

export const bankSchemas: BankSchemaConfig[] = [
  {
    bankName: "Aditya Birla",
    schema: adityaBirlaSchema,
    templatesAndFooters: 
      { 
      "ADITYA BIRLA-HL" :"ADITYA BIRLA HOUSING FINANCE LIMITED" ,
      "ADITYA BIRLA-ML" : "ADITYA BIRLA CAPITAL LIMITED" ,
      "ADITYA BIRLA-STSL" : "ADITYA BIRLA CAPITAL LIMITED" 
    },
  },
  {
    bankName: "Ambit",
    schema: ambitSchema,
    templatesAndFooters: {
      "AMBIT-HL" : "Ambit Finvest Pvt. Ltd." ,
    },
  },
  {
    bankName: "Ambit-MSME",
    schema: ambitMsmeSchema,
    templatesAndFooters: {
      "AMBIT-MSME" : "Ambit Finvest Pvt. Ltd." ,
    },
  },
  {
    bankName: "Axis Finance",
    schema: axisFinanceSchema,
    templatesAndFooters: {
      "AXIS FINANCE-HL" : "AXIS FINANCE LIMITED" ,
    },
  },
  {
    bankName: "Axis Finance UBL Above 10L",
    schema: axisFinanceUblAbove10lSchema,
    templatesAndFooters: {
      "AXIS FINANCE-UBL" : "AXIS FINANCE LIMITED" ,
    },
  },
  {
    bankName: "Axis Finance UBL Below 10L",
    schema: axisFinanceUblAbove10lSchema,
    templatesAndFooters: {
      "AXIS FINANCE-UBL" : "AXIS FINANCE LIMITED" ,
    },
  },
  {
    bankName: "Axis Bank",
    schema: axisBankSchema,
    templatesAndFooters: {
      "AXIS BANK" : "AXIS BANK LIMITED" ,
    },
  },
  {
    bankName: "Axis Agri",
    schema: axisAgriSchema,
    templatesAndFooters: {
      "AXIS AGRI" : "AXIS BANK LIMITED" ,
      "AXIS BUSINESS AGRI" : "AXIS BANK LIMITED" ,
    },
  },
  {
    bankName: "Chola",
    schema: cholaSchema,
    templatesAndFooters: {
      "CHOLA-HL" : "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LIMITED" ,
      "CHOLA-ML" : "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LIMITED" ,
    },
  },
  {
    bankName: "DCB",
    schema: dcbSchema,
    templatesAndFooters: {
      "DCB BANK" : "DCB BANK LIMITED" ,
    },
  },
  {
    bankName: "Arka Fincap",
    schema: arkaFincapSchema,
    templatesAndFooters: {
      "ARKA FINCAP" : "Arka Fincap Limited" ,
      "CENTRUM" : "Centrum Housing Finance Limited" ,
      "CENT BANK" : "CENT BANK HOME FINANCE LIMITED" ,
      "CLIX CAPITAL-HL" : "Clix Capital Services Pvt. Ltd." ,
      "CLIX CAPITAL-UBL" : "Clix Capital Services Pvt. Ltd." ,
      "EASY HL" : "Easy Home Finance Limited" ,
      "FED BANK (PD&LIP)" : "Fedbank Financial Services Ltd." ,
      "GODREJ-HL" : "GODREJ FINANCE LTD" ,
      "GODREJ-UBL" : "GODREJ FINANCE LTD" ,
      "INDUSIND" : "INDUSIND BANK LIMITED" ,
      "KOTAK" : "Kotak Mahindra Prime Ltd." ,
      "MUTHOOT-HL" : "muthoot housing finance company limited" ,
      "MUTHOOT FINCORP (PD & LIP)" : "MUTHOOT FINCORP LIMITED" ,
      "NIDO HOME FINANCE" : "NIDO HOME FINANCE LIMITED" ,
      "NORTHERN ARC" : "NORTHERN ARC CAPITAL LIMITED" ,
      "NIPUN" : "Nipun Projects and Finance Private Limited" ,
      "PIRAMAL (PD, AIP, LIP)" : "Piramal Finance Limited" ,
      "PNB" : "PNB HOUSING FINANCE LIMITED" ,
      "SAMMAAN" : "Sammaan Finserve Limited" ,
      "SMFG-ML (MICRO & MASS)" : "SMFG INDIA CREDIT COMPANY LIMITED" ,
      "SMFG-HL" : "SMFG INDIA HOME FINANCE COMPANY LIMITED" ,
      "TATA CAPITAL-FSL" : "TATA CAPITAL LIMITED" ,
      "TATA CAPITAL-HFL" : "TATA CAPITAL HOUSING FINANCE LIMITED" ,
      "TRUHOME (PD & LIP)" : "TRUHOME FINANCE LIMITED" ,
      "VERITAS" : "VERITAS FINANCE LIMITED" ,
    },
  },
  { 
    bankName: "Hero Fincorp",
    schema: heroFincorpSchema,
    templatesAndFooters: {
      "HERO FINCORP" : "HERO FINCORP LIMITED" ,
    },
  },
  {
    bankName: "HeroHousing-Salaried",
    schema: herohousingSalariedSchema,
    templatesAndFooters: {
      "HERO HOUSING" : "HERO HOUSING FINANCE LIMITED" ,
    },
  },
  {
    bankName: "HeroHousing-Self",
    schema: herohousingSelfSchema,
    templatesAndFooters: {
      "HERO HOUSING" : "HERO HOUSING FINANCE LIMITED" ,
    },
  },
  {
    bankName: "ICICI",
    schema: iciciSchema,
    templatesAndFooters: {
      "ICICI" : "icici home finance company limited" ,
    },
  },
  {
    bankName: "IDFC HL & ML",
    schema: idfcHlMlSchema,
    templatesAndFooters: {
      "IDFC FIRST-HL" : "IDFC FIRST BANK LIMITED" ,
      "IDFC FIRST-ML" : "IDFC FIRST BANK LIMITED" ,
    },
  },
  {
    bankName: "IDFC PL",
    schema: idfcPlSchema,
    templatesAndFooters: {
      "IDFC FIRST-PL" : "IDFC FIRST BANK LIMITED" ,
    },
  },
  {
    bankName: "IIFL",
    schema: iiflSchema,
    templatesAndFooters: {
      "IIFL" : "IIFL HOME FINANCE LIMITED" ,
    },
  },
  {
    bankName: "India Shelter SENP",
    schema: indiaShelterSenpSchema,
    templatesAndFooters: {
      "INDIA SHELTER" : "India Shelter Finance Corporation Ltd." ,
    },
  },
  {
    bankName: "India Shelter Salaried",
    schema: indiaShelterSalariedSchema,
    templatesAndFooters: {
      "INDIA SHELTER" : "India Shelter Finance Corporation Ltd." ,
    },
  },
  {
    bankName: "INCRED",
    schema: incredSchema,
    templatesAndFooters: {
      "INCRED/KKR India Financial Services Limited" : "KKR India Financial Services Limited" ,
    },
  },
  {
    bankName: "Jana Salaried",
    schema: janaSalariedSchema,
    templatesAndFooters: {
      "JANA SMALL FINANCE BANK LIMITED" : "JANA SMALL FINANCE BANK LIMITED" ,
    },
  },
  {
    bankName: "Jana Senp Above 50l",
    schema: janaSenpAbove50lSchema,
    templatesAndFooters: {
      "JANA SMALL FINANCE BANK LIMITED" : "JANA SMALL FINANCE BANK LIMITED" ,
    },
  },
  {
    bankName: "Jana Senp Below 50l",
    schema: janaSenpBelow50lSchema,
    templatesAndFooters: {
      "JANA SMALL FINANCE BANK LIMITED" : "JANA SMALL FINANCE BANK LIMITED" ,
    },
  },
  {
    bankName: "Niwas Salaried",
    schema: niwasSalariedSchema,
    templatesAndFooters: {
      "NIWAS" : "NIWAS HOUSING FINANCE PRIVATE LIMITED" ,
    },
  },
  {
    bankName: "Niwas Senp",
    schema: niwasSenpSchema,
    templatesAndFooters: {
      "NIWAS" : "NIWAS HOUSING FINANCE PRIVATE LIMITED" ,
    },
  },
  {
    bankName: "RBL",
    schema: rblSchema,
    templatesAndFooters: {
      "RBL BANK (PD & LIP)" : "RBL BANK LIMITED" ,
    },
  },
  {
    bankName: "SMFG SME",
    schema: smfgSmeSchema,
    templatesAndFooters: {
      "SMFG-SME" : "SMFG INDIA CREDIT COMPANY LIMITED" ,
    },
  },
  {
    bankName: "Tata Ubl",
    schema: tataUblSchema,
    templatesAndFooters: {
      "TATA CAPITAL-UBL" : "TATA CAPITAL LIMITED" ,
    },
  },
  {
    bankName: "Yes Bank",
    schema: yesBankSchema,
    templatesAndFooters: {
      "YES BANK-HL" : "YES BANK LIMITED" ,
    },
  },
];

// Legacy formSchema for backward compatibility
export const formSchema = bankSchemas.reduce(
  (acc, config) => {
    acc[config.bankName] = config.schema;
    return acc;
  },
  {} as Record<string, any>
) as Record<string, any>;

export type FormSchema = typeof formSchema;
export type BankName = keyof typeof formSchema;
export const BANK_NAMES = Object.keys(formSchema) as BankName[];

// Additional templates that don't have schemas yet
// const additionalTemplates = [
//   "CENTRUM",
//   "CENT BANK",
//   "CLIX CAPITAL-HL",
//   "CLIX CAPITAL-UBL",
//   "EASY HL",
//   "FED BANK (PD&LIP)",
//   "GODREJ-HL",
//   "GODREJ-UBL",
//   "INDUSIND",
//   "JANA SMALL FINANCE BANK LIMITED",
//   "KOTAK",
//   "MUTHOOT-HL",
//   "MUTHOOT FINCORP (PD & LIP)",
//   "NIDO HOME FINANCE",
//   "NORTHERN ARC",
//   "NIPUN",
//   "PIRAMAL (PD, AIP, LIP)",
//   "PNB",
//   "SAMMAAN",
//   "SMFG-ML (MICRO & MASS)",
//   "SMFG-HL",
//   "TATA CAPITAL-FSL",
//   "TATA CAPITAL-HFL",
//   "TRUHOME (PD & LIP)",
//   "VERITAS",
// ];

// Generate template options from bank schemas using templatesAndFooters keys
export const getAllTemplateOptions = (): Array<{
  value: string;
  label: string;
}> => {
  const templates: Array<{ value: string; label: string }> = [];

  // Add templates from bank schemas - use keys from templatesAndFooters
  bankSchemas.forEach((config) => {
    if (config.templatesAndFooters) {
      Object.keys(config.templatesAndFooters).forEach((template) => {
        templates.push({ value: template, label: template });
      });
    }
  });

  // Remove duplicates and sort
  const uniqueTemplates = Array.from(
    new Map(templates.map((t) => [t.value, t])).values()
  );

  return uniqueTemplates.sort((a, b) => a.label.localeCompare(b.label));
};

/**
 * Get footer name from template name by looking up in bankSchemas
 * @param templateName - The template name selected (e.g., "ADITYA BIRLA-HL")
 * @returns The corresponding footer name (e.g., "ADITYA BIRLA HOUSING FINANCE LIMITED") or null if not found
 */
export const getFooterNameFromTemplate = (templateName: string): string | null => {
  if (!templateName) return null;

  for (const config of bankSchemas) {
    if (config.templatesAndFooters && config.templatesAndFooters[templateName]) {
      return config.templatesAndFooters[templateName];
    }
  }

  return null;
};

/**
 * Get template names from bankName (returns all templates for that bank)
 * @param bankName - The bank name (e.g., "Aditya Birla")
 * @returns Array of template names or empty array if not found
 */
export const getTemplateNamesFromBank = (bankName: string): string[] => {
  if (!bankName) return [];

  const matchingConfig = bankSchemas.find(
    (config) => config.bankName === bankName
  );

  if (matchingConfig && matchingConfig.templatesAndFooters) {
    return Object.keys(matchingConfig.templatesAndFooters);
  }

  return [];
};

/**
 * Get bankName from templateName by looking up in bankSchemas
 * @param templateName - The template name (e.g., "ADITYA BIRLA-HL")
 * @returns The corresponding bankName (e.g., "Aditya Birla") or null if not found
 */
export const getBankNameFromTemplate = (templateName: string): string | null => {
  if (!templateName) return null;

  for (const config of bankSchemas) {
    if (config.templatesAndFooters && config.templatesAndFooters[templateName]) {
      return config.bankName;
    }
  }

  return null;
};

/**
 * Get schema from templateName by looking up in bankSchemas
 * @param templateName - The template name (e.g., "ADITYA BIRLA-HL")
 * @returns The corresponding schema or null if not found
 */
export const getSchemaFromTemplate = (templateName: string): any | null => {
  if (!templateName) return null;

  for (const config of bankSchemas) {
    if (config.templatesAndFooters && config.templatesAndFooters[templateName]) {
      return config.schema;
    }
  }

  return null;
};

/**
 * Get BankSchemaConfig from templateName
 * @param templateName - The template name (e.g., "ADITYA BIRLA-HL")
 * @returns The matching BankSchemaConfig or null if not found
 */
export const getBankConfigFromTemplate = (templateName: string): BankSchemaConfig | null => {
  if (!templateName) return null;

  for (const config of bankSchemas) {
    if (config.templatesAndFooters && config.templatesAndFooters[templateName]) {
      return config;
    }
  }

  return null;
};
