// Auto-generated by scripts/split-forms.js

import axisFinanceUblAbove10lSchema from './axis-finance-ubl-above-10l';
import axisFinanceUblBelow10lSchema from './axis-finance-ubl-below-10l';
import axisBankSchema from './axis-bank';
import arkaFincapSchema from './arka-fincap';
import tataUblSchema from './tata-ubl';
import rblSchema from './rbl';
import herohousingSalariedSchema from './herohousing-salaried';
import herohousingSelfSchema from './herohousing-self';
import cholaSchema from './chola';
import dcbSchema from './dcb';
import heroFincorpSchema from './hero-fincorp';
import iciciSchema from './icici';
import idfcHlMlSchema from './idfc-hl-ml';
import idfcPlSchema from './idfc-pl';
import iiflSchema from './iifl';
import niwasSalariedSchema from './niwas-salaried';
import niwasSenpSchema from './niwas-senp';
import yesBankSchema from './yes-bank';
import smfgSmeSchema from './smfg-sme';
import indiaShelterSenpSchema from './india-shelter-senp';
import indiaShelterSalariedSchema from './india-shelter-salaried';
import incredSchema from './incred';
import axisAgriSchema from './axis-agri';
import adityaBirlaSchema from './aditya-birla';
import ambitSchema from './ambit';
import axisFinanceSchema from './axis-finance';

export const formSchema = {
  "Axis Finance UBL Above 10L": axisFinanceUblAbove10lSchema,
  "Axis Finance UBL Below 10L": axisFinanceUblBelow10lSchema,
  "Axis Bank": axisBankSchema,
  "Arka Fincap": arkaFincapSchema,
  "Tata Ubl": tataUblSchema,
  "RBL": rblSchema,
  "HeroHousing-Salaried": herohousingSalariedSchema,
  "HeroHousing-Self": herohousingSelfSchema,
  "Chola": cholaSchema,
  "DCB": dcbSchema,
  "Hero Fincorp": heroFincorpSchema,
  "ICICI": iciciSchema,
  "IDFC HL & ML": idfcHlMlSchema,
  "IDFC PL": idfcPlSchema,
  "IIFL": iiflSchema,
  "Niwas Salaried": niwasSalariedSchema,
  "Niwas Senp": niwasSenpSchema,
  "Yes Bank": yesBankSchema,
  "SMFG SME": smfgSmeSchema,
  "India Shelter SENP": indiaShelterSenpSchema,
  "India Shelter Salaried": indiaShelterSalariedSchema,
  "INCRED": incredSchema,
  "Axis Agri": axisAgriSchema,
  "Aditya Birla": adityaBirlaSchema,
  "Ambit": ambitSchema,
  "Axis Finance": axisFinanceSchema
} as const;

export type FormSchema = typeof formSchema;
export type BankName = keyof typeof formSchema;
export const BANK_NAMES = Object.keys(formSchema) as BankName[];
