// Auto-generated by scripts/split-forms.js

import axisFinanceUblAbove10lSchema from "./axis-finance-ubl-above-10l";
import axisFinanceUblBelow10lSchema from "./axis-finance-ubl-below-10l";
import axisBankSchema from "./axis-bank";
import arkaFincapSchema from "./arka-fincap";
import tataUblSchema from "./tata-ubl";
import rblSchema from "./rbl";
import herohousingSalariedSchema from "./herohousing-salaried";
import herohousingSelfSchema from "./herohousing-self";
import cholaSchema from "./chola";
import dcbSchema from "./dcb";
import heroFincorpSchema from "./hero-fincorp";
import iciciSchema from "./icici";
import idfcHlMlSchema from "./idfc-hl-ml";
import idfcPlSchema from "./idfc-pl";
import iiflSchema from "./iifl";
import niwasSalariedSchema from "./niwas-salaried";
import niwasSenpSchema from "./niwas-senp";
import yesBankSchema from "./yes-bank";
import smfgSmeSchema from "./smfg-sme";
import indiaShelterSenpSchema from "./india-shelter-senp";
import indiaShelterSalariedSchema from "./india-shelter-salaried";
import incredSchema from "./incred";
import axisAgriSchema from "./axis-agri";
import adityaBirlaSchema from "./aditya-birla";
import ambitSchema from "./ambit";
import ambitMsmeSchema from "./ambit-msme";
import axisFinanceSchema from "./axis-finance";
import janaSalariedSchema from "./jana-salaried";
import janaSenpAbove50lSchema from "./jana-senp-above-50l";
import janaSenpBelow50lSchema from "./jana-senp-below-50l";

export interface BankSchemaConfig {
  bankName: string;
  schema: any;
  templates: string[];
}

export const bankSchemas: BankSchemaConfig[] = [
  {
    bankName: "Aditya Birla",
    schema: adityaBirlaSchema,
    templates: ["ADITYA BIRLA-HL", "ADITYA BIRLA-ML", "ADITYA BIRLA-STSL"],
  },
  {
    bankName: "Ambit",
    schema: ambitSchema,
    templates: ["AMBIT-HL"],
  },
  {
    bankName: "Ambit-MSME",
    schema: ambitMsmeSchema,
    templates: ["AMBIT-MSME"],
  },
  {
    bankName: "Axis Finance",
    schema: axisFinanceSchema,
    templates: ["AXIS FINANCE-HL"],
  },
  {
    bankName: "Axis Finance UBL Above 10L",
    schema: axisFinanceUblAbove10lSchema,
    templates: ["AXIS FINANCE-UBL"],
  },
  {
    bankName: "Axis Finance UBL Below 10L",
    schema: axisFinanceUblBelow10lSchema,
    templates: ["AXIS FINANCE-UBL"],
  },
  {
    bankName: "Axis Bank",
    schema: axisBankSchema,
    templates: ["AXIS BANK"],
  },
  {
    bankName: "Axis Agri",
    schema: axisAgriSchema,
    templates: ["AXIS AGRI", "AXIS BUSINESS AGRI"],
  },
  {
    bankName: "Arka Fincap",
    schema: arkaFincapSchema,
    templates: ["ARKA FINCAP","CENTRUM","CENT BANK","CLIX CAPITAL-UBL","EASY HL","FED BANK (PD&LIP)","GODREJ-HL","GODREJ-UBL","INDUSIND","KOTAK","MUTHOOT-HL","MUTHOOT FINCORP (PD & LIP)","NIDO HOME FINANCE","NORTHERN ARC","NIPUN","PIRAMAL (PD, AIP, LIP)","PNB","SAMMAAN","SMFG-ML (MICRO & MASS)","SMFG-HL","TATA CAPITAL-FSL","TATA CAPITAL-HFL","TRUHOME (PD & LIP)","VERITAS"],
  },
  {
    bankName: "Chola",
    schema: cholaSchema,
    templates: ["CHOLA-HL", "CHOLA-SME"],
  },
  {
    bankName: "DCB",
    schema: dcbSchema,
    templates: ["DCB BANK"],
  },
  {
    bankName: "Hero Fincorp",
    schema: heroFincorpSchema,
    templates: ["HERO FINCORP"],
  },
  {
    bankName: "HeroHousing-Salaried",
    schema: herohousingSalariedSchema,
    templates: ["HERO HOUSING"],
  },
  {
    bankName: "HeroHousing-Self",
    schema: herohousingSelfSchema,
    templates: ["HERO HOUSING"],
  },
  {
    bankName: "ICICI",
    schema: iciciSchema,
    templates: ["ICICI"],
  },
  {
    bankName: "IDFC HL & ML",
    schema: idfcHlMlSchema,
    templates: ["IDFC FIRST-HL", "IDFC FIRST-ML"],
  },
  {
    bankName: "IDFC PL",
    schema: idfcPlSchema,
    templates: ["IDFC FIRST-PL"],
  },
  {
    bankName: "IIFL",
    schema: iiflSchema,
    templates: ["IIFL"],
  },
  {
    bankName: "India Shelter SENP",
    schema: indiaShelterSenpSchema,
    templates: ["INDIA SHELTER"],
  },
  {
    bankName: "India Shelter Salaried",
    schema: indiaShelterSalariedSchema,
    templates: ["INDIA SHELTER"],
  },
  {
    bankName: "INCRED",
    schema: incredSchema,
    templates: ["INCRED/KKR India Financial Services Limited"],
  },
  {
    bankName: "Jana Salaried",
    schema: janaSalariedSchema,
    templates: ["JANA SMALL FINANCE BANK LIMITED"],
  },
  {
    bankName: "Jana Senp Above 50l",
    schema: janaSenpAbove50lSchema,
    templates: ["JANA SMALL FINANCE BANK LIMITED"],
  },
  {
    bankName: "Jana Senp Below 50l",
    schema: janaSenpBelow50lSchema,
    templates: ["JANA SMALL FINANCE BANK LIMITED"],
  },
  {
    bankName: "Niwas Salaried",
    schema: niwasSalariedSchema,
    templates: ["NIWAS"],
  },
  {
    bankName: "Niwas Senp",
    schema: niwasSenpSchema,
    templates: ["NIWAS"],
  },
  {
    bankName: "RBL",
    schema: rblSchema,
    templates: ["RBL BANK (PD & LIP)"],
  },
  {
    bankName: "SMFG SME",
    schema: smfgSmeSchema,
    templates: ["SMFG-SME"],
  },
  {
    bankName: "Tata Ubl",
    schema: tataUblSchema,
    templates: ["TATA CAPITAL-UBL"],
  },
  {
    bankName: "Yes Bank",
    schema: yesBankSchema,
    templates: ["YES BANK-HL"],
  },
];

// Legacy formSchema for backward compatibility
export const formSchema = bankSchemas.reduce(
  (acc, config) => {
    acc[config.bankName] = config.schema;
    return acc;
  },
  {} as Record<string, any>
) as Record<string, any>;

export type FormSchema = typeof formSchema;
export type BankName = keyof typeof formSchema;
export const BANK_NAMES = Object.keys(formSchema) as BankName[];

// Additional templates that don't have schemas yet
const additionalTemplates = [
  "CENTRUM",
  "CENT BANK",
  "CLIX CAPITAL-HL",
  "CLIX CAPITAL-UBL",
  "EASY HL",
  "FED BANK (PD&LIP)",
  "GODREJ-HL",
  "GODREJ-UBL",
  "INDUSIND",
  "JANA SMALL FINANCE BANK LIMITED",
  "KOTAK",
  "MUTHOOT-HL",
  "MUTHOOT FINCORP (PD & LIP)",
  "NIDO HOME FINANCE",
  "NORTHERN ARC",
  "NIPUN",
  "PIRAMAL (PD, AIP, LIP)",
  "PNB",
  "SAMMAAN",
  "SMFG-ML (MICRO & MASS)",
  "SMFG-HL",
  "TATA CAPITAL-FSL",
  "TATA CAPITAL-HFL",
  "TRUHOME (PD & LIP)",
  "VERITAS",
];

// Generate template options from bank schemas and additional templates
export const getAllTemplateOptions = (): Array<{
  value: string;
  label: string;
}> => {
  const templates: Array<{ value: string; label: string }> = [];

  // Add templates from bank schemas
  bankSchemas.forEach((config) => {
    config.templates.forEach((template) => {
      templates.push({ value: template, label: template });
    });
  });

  // Add additional templates that don't have schemas yet
  additionalTemplates.forEach((template) => {
    templates.push({ value: template, label: template });
  });

  // Remove duplicates and sort
  const uniqueTemplates = Array.from(
    new Map(templates.map((t) => [t.value, t])).values()
  );

  return uniqueTemplates.sort((a, b) => a.label.localeCompare(b.label));
};
