const fs = require("fs");
const path = require("path");

function slugify(input) {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

function toCamelCase(input) {
  const words = input
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/);
  if (words.length === 0) return "schema";
  const first = words[0].toLowerCase().replace(/^[^a-zA-Z_]+/, "");
  const rest = words
    .slice(1)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());
  let name = [first, ...rest].join("");
  if (!name || /^(?:\d|$)/.test(name)) name = "_" + name;
  return name + "Schema";
}

function extractFormObjectLiteral(source) {
  const exportIdx = source.indexOf("export const formSchema");
  if (exportIdx === -1)
    throw new Error('Could not find "export const formSchema"');
  const afterExport = source.indexOf("=", exportIdx);
  if (afterExport === -1)
    throw new Error("Could not find assignment for formSchema");
  const firstBrace = source.indexOf("{", afterExport);
  if (firstBrace === -1)
    throw new Error("Could not find opening brace for formSchema");

  // Find the last occurrence of "};" and take the preceding '}' as the end of the object literal
  const lastTerminator = source.lastIndexOf("};");
  if (lastTerminator === -1)
    throw new Error('Could not find closing "};" for formSchema');
  const endBrace = source.lastIndexOf("}", lastTerminator);
  if (endBrace === -1)
    throw new Error("Could not find closing brace for formSchema");

  return source.slice(firstBrace, endBrace + 1);
}

function main() {
  const repoRoot = path.resolve(__dirname, "..");
  const backendSrc = path.resolve(repoRoot, "apps", "backend", "src");
  const formsTsPath = path.resolve(backendSrc, "forms.ts");
  const outDir = path.resolve(backendSrc, "modules", "loan", "forms-schema");

  const source = fs.readFileSync(formsTsPath, "utf-8");
  const objectLiteral = extractFormObjectLiteral(source);

  // Evaluate the object literal safely
  // eslint-disable-next-line no-new-func
  const formObj = new Function(`return (${objectLiteral});`)();
  if (!formObj || typeof formObj !== "object" || Array.isArray(formObj)) {
    throw new Error("Parsed formSchema is not an object");
  }

  fs.mkdirSync(outDir, { recursive: true });

  // Clear existing generated files (but keep the directory)
  for (const file of fs.readdirSync(outDir)) {
    const filePath = path.join(outDir, file);
    if (fs.lstatSync(filePath).isFile()) fs.unlinkSync(filePath);
  }

  const importLines = [];
  const mapEntries = [];

  for (const [bankName, schema] of Object.entries(formObj)) {
    const fileSlug = slugify(bankName);
    const varName = toCamelCase(bankName);
    const filePath = path.join(outDir, `${fileSlug}.ts`);
    const json = JSON.stringify(schema, null, 2);
    const fileContents = `export const ${varName} = ${json} as const;\nexport default ${varName};\n`;
    fs.writeFileSync(filePath, fileContents, "utf-8");
    importLines.push(`import ${varName} from './${fileSlug}';`);
    mapEntries.push(JSON.stringify(bankName) + ": " + varName);
  }

  const indexTs = [
    "// Auto-generated by scripts/split-forms.js\n",
    ...importLines,
    "",
    "export const formSchema = {",
    "  " + mapEntries.join(",\n  "),
    "} as const;\n",
    "export type FormSchema = typeof formSchema;\n",
    "export type BankName = keyof typeof formSchema;\n",
    "export const BANK_NAMES = Object.keys(formSchema) as BankName[];\n",
  ].join("\n");

  fs.writeFileSync(path.join(outDir, "index.ts"), indexTs, "utf-8");

  console.log(`Generated ${mapEntries.length} bank schema files in ${outDir}`);
}

main();
