export const loanTypeOptions = [
  { value: "Personal Loan", label: "Personal Loan" },
  { value: "Home Loan", label: "Home Loan" },
  { value: "Vehicle Loan", label: "Vehicle Loan" },
  { value: "Agricultural Loan", label: "Agricultural Loan" },
  { value: "Mortgage Loan", label: "Mortgage Loan" },
  { value: "Top-up Loan", label: "Top-up Loan" },
  { value: "Busienss Loan", label: "Business Loan" },
  { value: "Others", label: "Others" },
];

export const bankOptions = [
  { value: "TATA CAPITAL LIMITED", label: "TATA CAPITAL LIMITED" },
  {
    value: "TATA CAPITAL HOUSING FINANCE LIMITED",
    label: "TATA CAPITAL HOUSING FINANCE LIMITED",
  },
  {
    value: "INDIABULLS HOUSING FINANCE LTD",
    label: "INDIABULLS HOUSING FINANCE LTD",
  },
  {
    value: "IDFC FIRST FINANCIAL SERVICES LIMITED",
    label: "IDFC FIRST FINANCIAL SERVICES LIMITED",
  },
  {
    value: "IIFL HOUSING FINANCE LIMITED",
    label: "IIFL HOUSING FINANCE LIMITED",
  },
  {
    value: "ADITYA BIRLA HOUSING FINANCE LIMITED",
    label: "ADITYA BIRLA HOUSING FINANCE LIMITED",
  },
  {
    value: "PUNJAB NATIONAL BANK HOUSING FINANCE LIMITED",
    label: "PUNJAB NATIONAL BANK HOUSING FINANCE LIMITED",
  },
  {
    value: "INDUSIND HOUSING FINANCE LIMITED",
    label: "INDUSIND HOUSING FINANCE LIMITED",
  },
  { value: "INDUSIND BANK LIMITED", label: "INDUSIND BANK LIMITED" },
  {
    value: "CENTRUM HOUSING FINANCE LTD",
    label: "CENTRUM HOUSING FINANCE LTD",
  },
  {
    value: "STATE BANK OF INDIA –IT VERIFICATION AGENCY",
    label: "STATE BANK OF INDIA –IT VERIFICATION AGENCY",
  },
  { value: "AXIS FINANCE LTD", label: "AXIS FINANCE LTD" },
  {
    value: "FULLERTON HOUSING FINANCE LTD",
    label: "FULLERTON HOUSING FINANCE LTD",
  },
  {
    value: "FULLERTON CREDIT COMPANY LTD",
    label: "FULLERTON CREDIT COMPANY LTD",
  },
  { value: "AHAM HOUSING FINANCE LTD", label: "AHAM HOUSING FINANCE LTD" },
  { value: "ICICI HOME FINANCE LTD", label: "ICICI HOME FINANCE LTD" },
  {
    value: "PIRAMAL HOUSING FINANCE LTD",
    label: "PIRAMAL HOUSING FINANCE LTD",
  },
  { value: "YES BANK LTD", label: "YES BANK LTD" },
  { value: "INCRED HOUSING FINANCE LTD", label: "INCRED HOUSING FINANCE LTD" },
  { value: "AMBIT FINVEST PVT.LTD", label: "AMBIT FINVEST PVT.LTD" },
  {
    value: "INDOSTAR HOME FINANCE PRIVATE LIMITED",
    label: "INDOSTAR HOME FINANCE PRIVATE LIMITED",
  },
  {
    value: "BANK OF INDIA – DUE DILIGENCE",
    label: "BANK OF INDIA – DUE DILIGENCE",
  },
  {
    value: "NEOGROWTH CREDIT PRIVATE LIMITED",
    label: "NEOGROWTH CREDIT PRIVATE LIMITED",
  },
  {
    value: "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LTD",
    label: "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LTD",
  },
  {
    value: "HOUSING DEVELOPMENT FINANCE CORPORATION LIMITED",
    label: "HOUSING DEVELOPMENT FINANCE CORPORATION LIMITED",
  },
  {
    value: "HIRANANDINI FINANCIAL SERVICES PRIVATE LTD",
    label: "HIRANANDINI FINANCIAL SERVICES PRIVATE LTD",
  },
  {
    value: "MUTHOOT HOUSING FINANCE COMPANY LIMITED",
    label: "MUTHOOT HOUSING FINANCE COMPANY LIMITED",
  },
  { value: "DCB BANK LTD", label: "DCB BANK LTD" },
  {
    value: "CANARA BANK – DUE DILIGENCE FOR THE ENTIRE STATE OF ANDHRA PRADESH",
    label: "CANARA BANK – DUE DILIGENCE FOR THE ENTIRE STATE OF ANDHRA PRADESH",
  },
  { value: "RBL BANK LIMITED", label: "RBL BANK LIMITED" },
  { value: "NORTHEN ARC CAPITAL LTD", label: "NORTHEN ARC CAPITAL LTD" },
  { value: "AXIS BANK LTD", label: "AXIS BANK LTD" },
  { value: "ARKA FINCAP LIMITED", label: "ARKA FINCAP LIMITED" },
  { value: "CENT BANK", label: "CENT BANK" },
  { value: "NIDO HOME FINANCE LIMITED", label: "NIDO HOME FINANCE LIMITED" },
  { value: "HERO FINCORP", label: "HERO FINCORP" },
  {
    value: "KOTAK MAHINDRA BANK LIMITED",
    label: "KOTAK MAHINDRA BANK LIMITED",
  },
  {
    value: "SHRIRAM HOUSING FINANCE LTD",
    label: "SHRIRAM HOUSING FINANCE LTD",
  },
  {
    value: "SHRIRAM CITY UNION FINANCE LTD",
    label: "SHRIRAM CITY UNION FINANCE LTD",
  },
  { value: "HERO HOUSING FINANCIAL LTD", label: "HERO HOUSING FINANCIAL LTD" },
  { value: "GODREJ CAPITAL", label: "GODREJ CAPITAL" },
  {
    value: "NIPUN PROJECTS AND FINANCE PVT LTD",
    label: "NIPUN PROJECTS AND FINANCE PVT LTD",
  },
  { value: "MUTHOOT FINANCE LIMITED", label: "MUTHOOT FINANCE LIMITED" },
];

export const pdBankOptions = [
  { value: "Axis Finance UBL Above 10L", label: "Axis Finance UBL Above 10L" },
  { value: "Axis Finance UBL Below 10L", label: "Axis Finance UBL Below 10L" },
  { value: "Axis Bank", label: "Axis Bank" },
  { value: "Arka Fincap", label: "Arka Fincap" },
  { value: "Tata Ubl", label: "Tata Ubl" },
  { value: "RBL", label: "RBL" },
  { value: "HeroHousing-Salaried", label: "HeroHousing-Salaried" },
  { value: "HeroHousing-Self", label: "HeroHousing-Self" },
  { value: "Chola", label: "Chola" },
  { value: "DCB", label: "DCB" },
  { value: "Hero Fincorp", label: "Hero Fincorp" },
  { value: "ICICI", label: "ICICI" },
  { value: "IDFC HL & ML", label: "IDFC HL & ML" },
  { value: "IDFC PL", label: "IDFC PL" },
  { value: "IIFL", label: "IIFL" },
  { value: "Niwas Salaried", label: "Niwas Salaried" },
  { value: "Niwas Senp", label: "Niwas Senp" },
  { value: "Yes Bank", label: "Yes Bank" },
  { value: "SMFG SME", label: "SMFG SME" },
  { value: "India Shelter SENP", label: "India Shelter SENP" },
  { value: "India Shelter Salaried", label: "India Shelter Salaried" },
  { value: "INCRED", label: "INCRED" },
  { value: "Axis Agri", label: "Axis Agri" },
  { value: "Aditya Birla", label: "Aditya Birla" },
  { value: "Ambit", label: "Ambit" },
  { value: "Axis Finance", label: "Axis Finance" },
  { value: "AMBIT-MSME", label: "AMBIT-MSME" },
  { value: "JANA BANK SELF EMPLOYED ABOVE 50 LAKHS", label: "JANA BANK SELF EMPLOYED ABOVE 50 LAKHS" },
  { value: "JANA BANK SELF EMPLOYED BELOW 50 LAKHS", label: "JANA BANK SELF EMPLOYED BELOW 50 LAKHS" },
  { value: "JANA BANK SALARIED", label: "JANA BANK SALARIED" },
];

export const templateNameOptions = [
  { value: "ADITYA BIRLA HOUSING FINANCE LIMITED", label: "ADITYA BIRLA HOUSING FINANCE LIMITED" },
  { value: "ADITYA BIRLA CAPITAL LIMITED", label: "ADITYA BIRLA CAPITAL LIMITED" },
  { value: "AMBIT FINVEST PVT. LTD.", label: "AMBIT FINVEST PVT. LTD." },
  { value: "AXIS FINANCE LIMITED", label: "AXIS FINANCE LIMITED" },
  { value: "AXIS BANK LIMITED", label: "AXIS BANK LIMITED" },
  { value: "ARKA FINCAP LIMITED", label: "ARKA FINCAP LIMITED" },
  { value: "CENTRUM HOUSING FINANCE LIMITED", label: "CENTRUM HOUSING FINANCE LIMITED" },
  { value: "CENT BANK HOME FINANCE LIMITED", label: "CENT BANK HOME FINANCE LIMITED" },
  { value: "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LIMITED", label: "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LIMITED" },
  { value: "CLIX CAPITAL SERVICES PVT. LTD.", label: "CLIX CAPITAL SERVICES PVT. LTD." },
  { value: "DCB BANK LIMITED", label: "DCB BANK LIMITED" },
  { value: "EASY HOME FINANCE LIMITED", label: "EASY HOME FINANCE LIMITED" },
  { value: "FEDBANK FINANCIAL SERVICES LTD.", label: "FEDBANK FINANCIAL SERVICES LTD." },
  { value: "GODREJ FINANCE LTD", label: "GODREJ FINANCE LTD" },
  { value: "HERO FINCORP LIMITED", label: "HERO FINCORP LIMITED" },
  { value: "HERO HOUSING FINANCE LIMITED", label: "HERO HOUSING FINANCE LIMITED" },
  { value: "ICICI HOME FINANCE COMPANY LIMITED", label: "ICICI HOME FINANCE COMPANY LIMITED" },
  { value: "IDFC FIRST BANK LIMITED", label: "IDFC FIRST BANK LIMITED" },
  { value: "IIFL HOME FINANCE LIMITED", label: "IIFL HOME FINANCE LIMITED" },
  { value: "KKR INDIA FINANCIAL SERVICES LIMITED", label: "KKR INDIA FINANCIAL SERVICES LIMITED" },
  { value: "INDUSIND BANK LIMITED", label: "INDUSIND BANK LIMITED" },
  { value: "INDIA SHELTER FINANCE CORPORATION LTD.", label: "INDIA SHELTER FINANCE CORPORATION LTD." },
  { value: "JANA SMALL FINANCE BANK LIMITED", label: "JANA SMALL FINANCE BANK LIMITED" },
  { value: "KOTAK MAHINDRA PRIME LTD.", label: "KOTAK MAHINDRA PRIME LTD." },
  { value: "MUTHOOT HOUSING FINANCE COMPANY LIMITED", label: "MUTHOOT HOUSING FINANCE COMPANY LIMITED" },
  { value: "MUTHOOT FINCORP LIMITED", label: "MUTHOOT FINCORP LIMITED" },
  { value: "NIDO HOME FINANCE LIMITED", label: "NIDO HOME FINANCE LIMITED" },
  { value: "NIWAS HOUSING FINANCE PRIVATE LIMITED", label: "NIWAS HOUSING FINANCE PRIVATE LIMITED" },
  { value: "NORTHERN ARC CAPITAL LIMITED", label: "NORTHERN ARC CAPITAL LIMITED" },
  { value: "NIPUN PROJECTS AND FINANCE PRIVATE LIMITED", label: "NIPUN PROJECTS AND FINANCE PRIVATE LIMITED" },
  { value: "PIRAMAL FINANCE LIMITED", label: "PIRAMAL FINANCE LIMITED" },
  { value: "PNB HOUSING FINANCE LIMITED", label: "PNB HOUSING FINANCE LIMITED" },
  { value: "RBL BANK LIMITED", label: "RBL BANK LIMITED" },
  { value: "SAMMAAN FINSERVE LIMITED", label: "SAMMAAN FINSERVE LIMITED" },
  { value: "SMFG INDIA CREDIT COMPANY LIMITED", label: "SMFG INDIA CREDIT COMPANY LIMITED" },
  { value: "SMFG INDIA HOME FINANCE COMPANY LIMITED", label: "SMFG INDIA HOME FINANCE COMPANY LIMITED" },
  { value: "TATA CAPITAL LIMITED", label: "TATA CAPITAL LIMITED" },
  { value: "TATA CAPITAL HOUSING FINANCE LIMITED", label: "TATA CAPITAL HOUSING FINANCE LIMITED" },
  { value: "TRUHOME FINANCE LIMITED", label: "TRUHOME FINANCE LIMITED" },
  { value: "VERITAS FINANCE LIMITED", label: "VERITAS FINANCE LIMITED" },
  { value: "YES BANK LIMITED", label: "YES BANK LIMITED" },
];

export const applicantTypeOptions = [
  { label: "Primary Applicant", value: "Primary Applicant" },
  { label: "Co-applicant 1 ", value: "Co-applicant 1" },
  { label: "Co-applicant 2 ", value: "Co-applicant 2" },
  { label: "Co-applicant 3 ", value: "Co-applicant 3" },
  { label: "Co-applicant 4 ", value: "Co-applicant 4" },
  { label: "Co-applicant 5 ", value: "Co-applicant 5" },
  { label: "Co-applicant 6 ", value: "Co-applicant 6" },
  { label: "Guarantor", value: "Guarantor" },
];
