export const loanTypeOptions = [
  { value: "Personal Loan", label: "Personal Loan" },
  { value: "Home Loan", label: "Home Loan" },
  { value: "Vehicle Loan", label: "Vehicle Loan" },
  { value: "Agricultural Loan", label: "Agricultural Loan" },
  { value: "Mortgage Loan", label: "Mortgage Loan" },
  { value: "Top-up Loan", label: "Top-up Loan" },
  { value: "Busienss Loan", label: "Business Loan" },
  { value: "Others", label: "Others" },
];

export const bankOptions = [
  { value: "TATA CAPITAL LIMITED", label: "TATA CAPITAL LIMITED" },
  {
    value: "TATA CAPITAL HOUSING FINANCE LIMITED",
    label: "TATA CAPITAL HOUSING FINANCE LIMITED",
  },
  {
    value: "INDIABULLS HOUSING FINANCE LTD",
    label: "INDIABULLS HOUSING FINANCE LTD",
  },
  {
    value: "IDFC FIRST FINANCIAL SERVICES LIMITED",
    label: "IDFC FIRST FINANCIAL SERVICES LIMITED",
  },
  {
    value: "IIFL HOUSING FINANCE LIMITED",
    label: "IIFL HOUSING FINANCE LIMITED",
  },
  {
    value: "ADITYA BIRLA HOUSING FINANCE LIMITED",
    label: "ADITYA BIRLA HOUSING FINANCE LIMITED",
  },
  {
    value: "PUNJAB NATIONAL BANK HOUSING FINANCE LIMITED",
    label: "PUNJAB NATIONAL BANK HOUSING FINANCE LIMITED",
  },
  {
    value: "INDUSIND HOUSING FINANCE LIMITED",
    label: "INDUSIND HOUSING FINANCE LIMITED",
  },
  { value: "INDUSIND BANK LIMITED", label: "INDUSIND BANK LIMITED" },
  {
    value: "CENTRUM HOUSING FINANCE LTD",
    label: "CENTRUM HOUSING FINANCE LTD",
  },
  {
    value: "STATE BANK OF INDIA –IT VERIFICATION AGENCY",
    label: "STATE BANK OF INDIA –IT VERIFICATION AGENCY",
  },
  { value: "AXIS FINANCE LTD", label: "AXIS FINANCE LTD" },
  {
    value: "FULLERTON HOUSING FINANCE LTD",
    label: "FULLERTON HOUSING FINANCE LTD",
  },
  {
    value: "FULLERTON CREDIT COMPANY LTD",
    label: "FULLERTON CREDIT COMPANY LTD",
  },
  { value: "AHAM HOUSING FINANCE LTD", label: "AHAM HOUSING FINANCE LTD" },
  { value: "ICICI HOME FINANCE LTD", label: "ICICI HOME FINANCE LTD" },
  {
    value: "PIRAMAL HOUSING FINANCE LTD",
    label: "PIRAMAL HOUSING FINANCE LTD",
  },
  { value: "YES BANK LTD", label: "YES BANK LTD" },
  { value: "INCRED HOUSING FINANCE LTD", label: "INCRED HOUSING FINANCE LTD" },
  { value: "AMBIT FINVEST PVT.LTD", label: "AMBIT FINVEST PVT.LTD" },
  {
    value: "INDOSTAR HOME FINANCE PRIVATE LIMITED",
    label: "INDOSTAR HOME FINANCE PRIVATE LIMITED",
  },
  {
    value: "BANK OF INDIA – DUE DILIGENCE",
    label: "BANK OF INDIA – DUE DILIGENCE",
  },
  {
    value: "NEOGROWTH CREDIT PRIVATE LIMITED",
    label: "NEOGROWTH CREDIT PRIVATE LIMITED",
  },
  {
    value: "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LTD",
    label: "CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LTD",
  },
  {
    value: "HOUSING DEVELOPMENT FINANCE CORPORATION LIMITED",
    label: "HOUSING DEVELOPMENT FINANCE CORPORATION LIMITED",
  },
  {
    value: "HIRANANDINI FINANCIAL SERVICES PRIVATE LTD",
    label: "HIRANANDINI FINANCIAL SERVICES PRIVATE LTD",
  },
  {
    value: "MUTHOOT HOUSING FINANCE COMPANY LIMITED",
    label: "MUTHOOT HOUSING FINANCE COMPANY LIMITED",
  },
  { value: "DCB BANK LTD", label: "DCB BANK LTD" },
  {
    value: "CANARA BANK – DUE DILIGENCE FOR THE ENTIRE STATE OF ANDHRA PRADESH",
    label: "CANARA BANK – DUE DILIGENCE FOR THE ENTIRE STATE OF ANDHRA PRADESH",
  },
  { value: "RBL BANK LIMITED", label: "RBL BANK LIMITED" },
  { value: "NORTHEN ARC CAPITAL LTD", label: "NORTHEN ARC CAPITAL LTD" },
  { value: "AXIS BANK LTD", label: "AXIS BANK LTD" },
  { value: "ARKA FINCAP LIMITED", label: "ARKA FINCAP LIMITED" },
  { value: "CENT BANK", label: "CENT BANK" },
  { value: "NIDO HOME FINANCE LIMITED", label: "NIDO HOME FINANCE LIMITED" },
  { value: "HERO FINCORP", label: "HERO FINCORP" },
  {
    value: "KOTAK MAHINDRA BANK LIMITED",
    label: "KOTAK MAHINDRA BANK LIMITED",
  },
  {
    value: "SHRIRAM HOUSING FINANCE LTD",
    label: "SHRIRAM HOUSING FINANCE LTD",
  },
  {
    value: "SHRIRAM CITY UNION FINANCE LTD",
    label: "SHRIRAM CITY UNION FINANCE LTD",
  },
  { value: "HERO HOUSING FINANCIAL LTD", label: "HERO HOUSING FINANCIAL LTD" },
  { value: "GODREJ CAPITAL", label: "GODREJ CAPITAL" },
  {
    value: "NIPUN PROJECTS AND FINANCE PVT LTD",
    label: "NIPUN PROJECTS AND FINANCE PVT LTD",
  },
  { value: "MUTHOOT FINANCE LIMITED", label: "MUTHOOT FINANCE LIMITED" },
];

export const pdBankOptions = [
  { value: "ADITYA BIRLA", label: "ADITYA BIRLA" },
  { value: "AMBIT", label: "AMBIT" },
  { value: "AMBIT-MSME", label: "AMBIT-MSME" },
  { value: "AXIS FINANCE", label: "AXIS FINANCE" },
  { value: "AXIS FINANCE UBL ABOVE 10 LAKHS", label: "AXIS FINANCE UBL ABOVE 10 LAKHS" },
  { value: "AXIS FINANCE UBL BELOW 10 LAKHS", label: "AXIS FINANCE UBL BELOW 10 LAKHS" },
  { value: "AXIS BANK", label: "AXIS BANK" },
  { value: "AXIS AGRI", label: "AXIS AGRI" },
  { value: "ARKA FINCAP", label: "ARKA FINCAP" },
  { value: "CHOLA", label: "CHOLA" },
  { value: "DCB BANK", label: "DCB BANK" },
  { value: "HERO FINCORP", label: "HERO FINCORP" },
  { value: "HERO HOUSING-SELF EMPLOYED", label: "HERO HOUSING-SELF EMPLOYED" },
  { value: "HERO HOUSING-SALARIED", label: "HERO HOUSING-SALARIED" },
  { value: "ICICI", label: "ICICI" },
  { value: "IDFC HL & ML", label: "IDFC HL & ML" },
  { value: "IDFC PL", label: "IDFC PL" },
  { value: "IIFL", label: "IIFL" },
  { value: "INCRED", label: "INCRED" },
  { value: "INDIA SHELTER SENP", label: "INDIA SHELTER SENP" },
  { value: "INDIA SHELTER SALARIED", label: "INDIA SHELTER SALARIED" },
  { value: "JANA BANK SELF EMPLOYED ABOVE 50 LAKHS", label: "JANA BANK SELF EMPLOYED ABOVE 50 LAKHS" },
  { value: "JANA BANK SELF EMPLOYED BELOW 50 LAKHS", label: "JANA BANK SELF EMPLOYED BELOW 50 LAKHS" },
  { value: "JANA BANK SALARIED", label: "JANA BANK SALARIED" },
  { value: "NIWAS SENP", label: "NIWAS SENP" },
  { value: "NIWAS SALARIED", label: "NIWAS SALARIED" },
  { value: "RBL", label: "RBL" },
  { value: "SMFG SME", label: "SMFG SME" },
  { value: "TATA UBL", label: "TATA UBL" },
  { value: "YES BANK", label: "YES BANK" },
];

export const templateNameOptions = [
  { value: "ADITYA BIRLA-HL", label: "ADITYA BIRLA-HL" },
  { value: "ADITYA BIRLA-ML", label: "ADITYA BIRLA-ML" },
  { value: "ADITYA BIRLA-STSL", label: "ADITYA BIRLA-STSL" },
  { value: "AMBIT-HL", label: "AMBIT-HL" },
  { value: "AMBIT-MSME", label: "AMBIT-MSME" },
  { value: "AXIS FINANCE-HL", label: "AXIS FINANCE-HL" },
  { value: "AXIS FINANCE-UBL", label: "AXIS FINANCE-UBL" },
  { value: "AXIS BANK", label: "AXIS BANK" },
  { value: "AXIS AGRI", label: "AXIS AGRI" },
  { value: "AXIS BUSINESS AGRI", label: "AXIS BUSINESS AGRI" },
  { value: "ARKA FINCAP", label: "ARKA FINCAP" },
  { value: "CENTRUM", label: "CENTRUM" },
  { value: "CENT BANK", label: "CENT BANK" },
  { value: "CHOLA-HL", label: "CHOLA-HL" },
  { value: "CHOLA-SME", label: "CHOLA-SME" },
  { value: "CLIX CAPITAL-HL", label: "CLIX CAPITAL-HL" },
  { value: "CLIX CAPITAL-UBL", label: "CLIX CAPITAL-UBL" },
  { value: "DCB BANK", label: "DCB BANK" },
  { value: "EASY HL", label: "EASY HL" },
  { value: "FED BANK (PD&LIP)", label: "FED BANK (PD&LIP)" },
  { value: "GODREJ-HL", label: "GODREJ-HL" },
  { value: "GODREJ-UBL", label: "GODREJ-UBL" },
  { value: "HERO FINCORP", label: "HERO FINCORP" },
  { value: "HERO HOUSING", label: "HERO HOUSING" },
  { value: "ICICI", label: "ICICI" },
  { value: "IDFC FIRST-HL", label: "IDFC FIRST-HL" },
  { value: "IDFC FIRST-ML", label: "IDFC FIRST-ML" },
  { value: "IDFC FIRST-PL", label: "IDFC FIRST-PL" },
  { value: "IIFL", label: "IIFL" },
  { value: "INCRED/KKR India Financial Services Limited", label: "INCRED/KKR India Financial Services Limited" },
  { value: "INDUSIND", label: "INDUSIND" },
  { value: "INDIA SHELTER", label: "INDIA SHELTER" },
  { value: "JANA SMALL FINANCE BANK LIMITED", label: "JANA SMALL FINANCE BANK LIMITED" },
  { value: "KOTAK", label: "KOTAK" },
  { value: "MUTHOOT-HL", label: "MUTHOOT-HL" },
  { value: "MUTHOOT FINCORP (PD & LIP)", label: "MUTHOOT FINCORP (PD & LIP)" },
  { value: "NIDO HOME FINANCE", label: "NIDO HOME FINANCE" },
  { value: "NIWAS", label: "NIWAS" },
  { value: "NORTHERN ARC", label: "NORTHERN ARC" },
  { value: "NIPUN", label: "NIPUN" },
  { value: "PIRAMAL (PD, AIP, LIP)", label: "PIRAMAL (PD, AIP, LIP)" },
  { value: "PNB", label: "PNB" },
  { value: "RBL BANK (PD & LIP)", label: "RBL BANK (PD & LIP)" },
  { value: "SAMMAAN", label: "SAMMAAN" },
  { value: "SMFG-ML (MICRO & MASS)", label: "SMFG-ML (MICRO & MASS)" },
  { value: "SMFG-HL", label: "SMFG-HL" },
  { value: "SMFG-SME", label: "SMFG-SME" },
  { value: "TATA CAPITAL-FSL", label: "TATA CAPITAL-FSL" },
  { value: "TATA CAPITAL-HFL", label: "TATA CAPITAL-HFL" },
  { value: "TATA CAPITAL-UBL", label: "TATA CAPITAL-UBL" },
  { value: "TRUHOME (PD & LIP)", label: "TRUHOME (PD & LIP)" },
  { value: "VERITAS", label: "VERITAS" },
  { value: "YES BANK-HL", label: "YES BANK-HL" },
];

export const applicantTypeOptions = [
  { label: "Primary Applicant", value: "Primary Applicant" },
  { label: "Co-applicant 1 ", value: "Co-applicant 1" },
  { label: "Co-applicant 2 ", value: "Co-applicant 2" },
  { label: "Co-applicant 3 ", value: "Co-applicant 3" },
  { label: "Co-applicant 4 ", value: "Co-applicant 4" },
  { label: "Co-applicant 5 ", value: "Co-applicant 5" },
  { label: "Co-applicant 6 ", value: "Co-applicant 6" },
  { label: "Guarantor", value: "Guarantor" },
];
