name: Deploy to Lightsail

on:
  push:
    branches:
      - development  # or whichever branch you want to deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code in app folder
        run: |
          cd /home/ubuntu/kowtha/apps/backend/
          git pull origin development

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./apps/backend

      - name: Build backend
        run: npm run build
        working-directory: ./apps/backend

      - name: Restart PM2
        run: pm2 restart backend
