name: CI/CD - Revopush

on:
  push:
    branches: [ revopush-cicd, development ]
  #workflow_dispatch:  # Uncomment if you want manual runs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: apps/mobile/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('apps/mobile/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        envkey_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        file_name: .env
        fail_on_empty: false
        directory: apps/mobile
        sort_keys: false

    - name: Verify .env file
      run: cat .env | grep REACT_APP_BASE_URL

    - name: Install dependencies
      run: npm install --force

    - name: Clear Metro cache
      run: npx react-native start --reset-cache & sleep 5; kill $!

    - name: Setup Revopush CLI
      uses: revopush/revopush-github-action@v1
      with:
        version: 'latest'
        accessKey: ${{ secrets.REVOPUSH_ACCESS_KEY }}

    - name: Release Android bundle
      run: revopush release-react kowtha-app android -d Staging
